canal_tp_sam_ecore_application_manager_choose_application:
    pattern: /change/{application}
    defaults: { _controller: CanalTPSamEcoreApplicationManagerBundle:Application:change }

canal_tp_sam_ecore_application_manager_toolbar:
    pattern: /toolbar
    defaults: { _controller: CanalTPSamEcoreApplicationManagerBundle:Application:toolbar }
