services:
    canal_tp_sam_ecore_routing_loader:
        class: CanalTP\SamEcoreApplicationManagerBundle\Routing\ApplicationRoutingLoader
        arguments:
            - '@canal_tp_sam.application.finder'
        tags:
            - { name: routing.loader }

    sam.event.check_access:
        class: CanalTP\SamEcoreApplicationManagerBundle\Event\CheckAccess
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    canal_tp_sam.perimeter.form.listener:
        class: CanalTP\SamEcoreApplicationManagerBundle\Form\EventListener\PerimeterSubscriber
        arguments:
            - '@sam.business_component'
            - '@security.context'
            - '@fos_user.user_manager'

    canal_tp_sam.application.finder:
        class: CanalTP\SamEcoreApplicationManagerBundle\Services\ApplicationFinder
        arguments:
            - '@service_container'
            - CanalTP\SamCoreBundle\Entity\Application

    sam.business_component:
        class: CanalTP\SamEcoreApplicationManagerBundle\Component\BusinessComponentRegistry
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@canal_tp_sam.application.finder'
