parameters:
    canal_tp_sam_ecore_application_registration.class: CanalTP\SamEcoreApplicationManagerBundle\Services\ApplicationRegistration
    canal_tp_sam_ecore_routing_loader.class: CanalTP\SamEcoreApplicationManagerBundle\Routing\ApplicationRoutingLoader
    canal_tp_sam_ecore_route_prefix: 'business'
    canal_tp_sam.perimeter.form.listener.class: CanalTP\SamEcoreApplicationManagerBundle\Form\EventListener\PerimeterSubscriber
    canal_tp_sam.application.finder: CanalTP\SamEcoreApplicationManagerBundle\Services\ApplicationFinder
    canal_tp_sam.application.entity: CanalTP\SamCoreBundle\Entity\Application
    sam.event.check_access.class: CanalTP\SamEcoreApplicationManagerBundle\Event\CheckAccess

services:
    # Service d'enregistrement des applications
    canal_tp_sam_ecore_application_registration:
        class: %canal_tp_sam_ecore_application_registration.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%kernel.bundles%'

    canal_tp_sam_ecore_routing_loader:
        class: %canal_tp_sam_ecore_routing_loader.class%
        arguments:
            - '%kernel.bundles%'
            - '%canal_tp_sam_ecore_route_prefix%'
            - '@service_container'
        tags:
            - { name: routing.loader }

    sam.event.check_access:
        class: %sam.event.check_access.class%
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    canal_tp_sam.perimeter.form.listener:
        class: %canal_tp_sam.perimeter.form.listener.class%
        arguments:
            - @sam.business_component
            - @security.context
            - @fos_user.user_manager

    canal_tp_sam.application.finder:
        class: %canal_tp_sam.application.finder%
        arguments:
            - @service_container
            - %canal_tp_sam.application.entity%
